### ISSUE TITLE
It doesn't work!

### ISSUE THREAD

**Issue by DumboJetEngine** [asheroto/UpdateRootCertificates#11]
I am not sure what Microsoft has done, but the used endpoints do not work anymore.
You get timeouts.

My Windows is broken, it cannot update itself, there is no working fix ANYWHERE, and stupid Microsoft has no correct documentation on how to update the trusted roots anywhere.

**Comment by asheroto** [comment]
Hi,

I don't understand. Are you getting an error with the program or script? What OS?

**Comment by DumboJetEngine** [comment]
Windows 10.
I have tried with the program, by hitting the endpoints directly, by using `certutils`, and who knows what else...
Everything fails.
It appears to me that these online Microsoft files are not accessible anymore.

Unless I have some DNS or firewall issue that I am not aware of...

**Comment by DumboJetEngine** [comment]
Hm...
I just tried hitting the endpoint with Opera's VPN and it worked.
So, it might be a DNS issue.
Weird...
I use CloudFlare DNS.

**Comment by asheroto** [comment]
Possibly. 😊 Yep, files are okay. You might try downloading the "Windows 10 Update Assistant" which is a separate Microsoft program specifically for fixing/forcing an update.
