### ISSUE TITLE
Don't have the latest version of disallowedcertstl.cab file?.

### ISSUE THREAD

**Issue by oklokl** [asheroto/UpdateRootCertificates#12]
Is it already the latest version... or is it an old file?.
If it's not the latest version... I wonder if there is a newer version.

#9
http://ctldl.windowsupdate.com/msdownload/update/v3/static/trustedr/en/disallowedcertstl.cab 2019?
I applied it normally.
thank you.

if not old.
is there a similar.. block list?.
thank you.

**Comment by asheroto** [comment]
If you look at the cab files in an archive viewer like WinRAR, it looks like the allowed was last modified in June, and the disallowed over a year ago. That's probably right, there aren't a ton of root certs to change that often.

This is still the official one as far as I can tell. Windows Updates usually gets it right nowadays.

![image](https://user-images.githubusercontent.com/49938263/184620886-ced023bd-3014-4b1b-b2d7-3e3c551d97ee.png)

![image](https://user-images.githubusercontent.com/49938263/184620918-260e37a3-bc5a-4d9b-8559-674fef96ea01.png)

**Comment by oklokl** [comment]
Thank you.
