### ISSUE TITLE
need .NET framework 4.0

### ISSUE THREAD

**Issue by ylx2016** [asheroto/UpdateRootCertificates#4]
can you build one without  .NET framework 4.0

**Comment by ylx2016** [comment]
NET4.0 is not included in the initial version of win7, so NET4.8 cannot be installed and this program cannot be run.

**Comment by asheroto** [comment]
The program is developed in Visual Studio, using VB.NET, so unfortunately it is required in order for the program to work.

It is built against .NET Framework 4.5, so as long as you have that edition it should work.   You can download the offline installer here: https://www.microsoft.com/en-us/download/details.aspx?id=30653

Or if you don't want to install .NET Framework at all, you can make a batch file described by "Alex" in the comments which effectively does the same thing as the program.  On Windows 7 I don't think curl is included as an alias in PowerShell, so you might have to download curl.exe to the system32 directory and then run the script.

See the comment from "Alex" here:
https://asher.tools/root-certificate-updater

![image](https://user-images.githubusercontent.com/49938263/140010634-2cc88b72-371d-4e5c-a4ef-a3980dd86c0d.png)

**Comment by asheroto** [comment]
Hello again,

I have replaced the CMD version with a PowerShell script.  Using the script does not require .NET Framework and should work as expected so long as PowerShell is installed.

Depending on your environment you may need to run `Set-ExecutionPolicy RemoteSigned -Force` before running any PowerShell scripts.

**Comment by asheroto** [comment]
Visit the main page:
https://github.com/asheroto/Root-Certificate-Updater

Or the releases page:
https://github.com/asheroto/Root-Certificate-Updater/releases
