### ISSUE TITLE
Can I run this on Win7?

### ISSUE THREAD

**Issue by tyeeman** [asheroto/UpdateRootCertificates#9]
I have a few programs that won't work with https on my win7 box. I have always used firefox for web browsing so I have never needed the OS certificates. Firefox has it's own I've read. So...I have a download manager (aria2c) that won't work. Installing these may help but I thought I should try at least. Spending days reading about tls, certificates, keys, still I can't seem to determine the procedure to fix all this. Sometimes I thought it was the certificates, then the cipher suite, then....?? Any tips?

Here is the best website I found to explain to add the current certificates. I think your app here does the same. 

http://woshub.com/updating-trusted-root-certificates-in-windows-10/

**Comment by asheroto** [comment]
The app just executes some basic commands, essentially doing what that article you referenced does. Nothing fancy. You should be able to run the the app or PowerShell script on Windows 7 and it will work. If not, then you can execute these commands in CMD (running as administrator) and it will do the same thing.

```
certutil -urlcache -f http://ctldl.windowsupdate.com/msdownload/update/v3/static/trustedr/en/authrootstl.cab authrootstl.cab
certutil -urlcache -f http://ctldl.windowsupdate.com/msdownload/update/v3/static/trustedr/en/disallowedcertstl.cab disallowedcertstl.cab

expand authrootstl.cab -R .\
expand disallowedcertstl.cab -R .\

certutil -addstore -f root authroot.stl
certutil -addstore -f disallowed disallowedcert.stl
```

That's all that the app does. It just downloads the latest root certificates from Microsoft, extracts the CAB files to get the STL files, then adds the STL files into the certificate store. :-)

If you get an error when running certutil, try downloading the CAB files using your web browser, extract the CAB files with 7-zip to get the STL files, then run certutil to add the STL files (last two lines).

**Comment by asheroto** [comment]
Also, Firefox still honors Windows root certificates to ensure security is up-to-par. Because Windows doesn't release updates for Windows 7 any more, its root certificates won't be updated by default. Updating the root certificates should take care of most of the issues you've been facing, I believe.

**Comment by tyeeman** [comment]
Is the .stl file just a list or the actual certificates? From a comment in that page I linked, it seems to be just a list??

**Comment by asheroto** [comment]
STL stands for certificate trust list. It is a list of trusted certificates. Keep in mind, certificates basically just text files that contain the information to cryptographically perform.

Example of base64 encoded certificate:
![image](https://user-images.githubusercontent.com/49938263/147435337-939b23ff-4420-4df7-9c73-ce7cdadbebe3.png)


Don't worry about the details bro, just do it! It won't hurt anything by installing the certs. 😊

**Comment by asheroto** [comment]
Just curious, why don't you just upgrade to Windows 10?

**Comment by asheroto** [comment]
If you really want to make sure they are all imported, you can open Certificate Manager (certmgr.msc) as Local Computer, then export all the certs from a working computer, then import those into the Windows 7 machine....
![jy7QYBsyEu](https://user-images.githubusercontent.com/49938263/147435755-cda7a270-ef82-48b2-8727-1f7fd3517555.gif)

**Comment by asheroto** [comment]
Make sure to import to Local Machine.

![image](https://user-images.githubusercontent.com/49938263/147435855-2bcd8b38-ef09-4b1b-9117-c902946130ce.png)

**Comment by ban2019** [comment]
@asheroto
I found this issue via Google search after I failed to install the patch for updating https certificate from Microsoft. It saved my Win7. Thank you so much!!
